/
-- INDUSTRY_EW#MODEL.ALL#GRAPH
CREATE PROPERTY GRAPH "INDUSTRY_EW#MODEL"."ALL#GRAPH" 
  VERTEX TABLES (
   "INDUSTRY_EW#MODEL"."BASE_VOLTAGE_CIM" AS "BASE_VOLTAGE_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "NOMINAL_VOLTAGE"),
   "INDUSTRY_EW#MODEL"."BATTERY_STORAGE_SYSTEM_SELF_REPORTED_POSSESSION" AS "BATTERY_STORAGE_SYSTEM_SELF_REPORTED_POSSESSION" KEY ("EMAIL","RECORDED_AT_DATE_TIME")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "EMAIL", "RECORDED_AT_DATE_TIME"),
   "INDUSTRY_EW#MODEL"."BREAKER_CIM" AS "BREAKER_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "DESCRIPTION", "IN_TRANSIT_TIME", "BREAKING_CAPACITY", "EQUIPMENT_CONTAINER", "ADDITIONAL_EQUIPMENT_CONTAINER", "LOCATION"),
   "INDUSTRY_EW#MODEL"."BUSBAR_SET_CIM" AS "BUSBAR_SET_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "DESCRIPTION", "EQUIPMENT_CONTAINER"),
   "INDUSTRY_EW#MODEL"."CONDUCTING_EQUIPMENT_CIM" AS "CONDUCTING_EQUIPMENT_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME"),
   "INDUSTRY_EW#MODEL"."CONNECTIVITY_NODE_CIM" AS "CONNECTIVITY_NODE_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME"),
   "INDUSTRY_EW#MODEL"."CONTACT_CENTER_CUSTOMER_CALL" AS "CONTACT_CENTER_CUSTOMER_CALL" KEY ("CONTACT_CENTER_CUSTOMER_CALL_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CONTACT_CENTER_CUSTOMER_CALL_ID", "TELEPHONE_COUNTRY_CODE", "TELEPHONE_NUMBER", "TELEPHONE_NUMBER_TYPE", "CALL_START_DATE_TIME", "CALL_END_DATE_TIME", "UTILITY_ACCOUNT_ID", "UTILITY_LOCATION_ID", "PARTY_ID", "CALL_REASON_TYPE", "CALL_DURATION_SECONDS", "WAIT_SECONDS_FOR_CUSTOMER", "TALK_INTERACTION_SECONDS", "HOLD_SECONDS_FOR_CUSTOMER", "WRAP_SECONDS_FOR_CSR", "CSR_ID", "CSR_NOTES", "CALL_TRANSCRIPT"),
   "INDUSTRY_EW#MODEL"."COORDINATE_SYSTEM_CIM" AS "COORDINATE_SYSTEM_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "CRS_URN"),
   "INDUSTRY_EW#MODEL"."CORE#GEO_UNIT_HIERARCHY" AS "CORE#GEO_UNIT_HIERARCHY" KEY ("GEO_UNIT_ID","CONTAINS_GEO_UNIT_ID")
      PROPERTIES ("GEO_UNIT_ID", "CONTAINS_GEO_UNIT_ID"),
   "INDUSTRY_EW#MODEL"."DATA_PRODUCT" AS "DATA_PRODUCT" KEY ("DATA_PRODUCT_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "DATA_PRODUCT_UUID", "DATA_PRODUCT_NAME", "DATA_PRODUCT_DESCRIPTION", "SOURCE_SYSTEM_UUID", "SOURCE_SYSTEM_NAME", "DATA_DEFINITION_TYPE", "PRIMARY_DATA_CONCEPT", "DATA_TECHNOLOGY_TYPE", "DATA_OWNER_ID", "SOURCE_SOFTWARE_OFFERING", "DEPLOYMENT_TIER", "SOURCE_ORGANIZATION_NAME", "SOURCE_DATA_MODEL_METADATA", "EXPECTED_REFRESH_FREQUENCY_MINUTES", "EXPECTED_RETENTION_DAYS"),
   "INDUSTRY_EW#MODEL"."DATA_PRODUCT_GEOGRAPHIC_COVERAGE" AS "DATA_PRODUCT_GEOGRAPHIC_COVERAGE" KEY ("DATA_PRODUCT_UUID","GEOGRAPHIC_OVERLAP_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "DATA_PRODUCT_UUID", "GEOGRAPHIC_OVERLAP_UUID", "COUNTRY_CODE", "SUBTERRITORY_CODE"),
   "INDUSTRY_EW#MODEL"."DATA_PRODUCT_OWNER" AS "DATA_PRODUCT_OWNER" KEY ("DATA_OWNER_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "DATA_OWNER_ID", "DATA_OWNER_NAME", "DATA_OWNER_EMAIL_ADDRESS", "DATA_OWNER_PROFILE_LINK"),
   "INDUSTRY_EW#MODEL"."DATA_PRODUCT_SCOPE" AS "DATA_PRODUCT_SCOPE" KEY ("DATA_PRODUCT_UUID","DATA_PRODUCT_SCOPE_TYPE")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "DATA_PRODUCT_UUID", "DATA_PRODUCT_SCOPE_TYPE"),
   "INDUSTRY_EW#MODEL"."DER_DEVICE" AS "DER_DEVICE" KEY ("DER_UNIQUE_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "DER_UNIQUE_ID", "DER_NAME", "DER_MANUFACTURER_DEVICE_ID", "DER_MANUFACTURER_DEVICE_MODEL", "DER_MANUFACTURER_DEVICE_SERIAL_NUMBER", "DER_MANUFACTURER_DEVICE_HARDWARE_VERSION", "DER_MANUFACTURER_DEVICE_SOFTWARE_VERSION", "DER_RESERVE_DURATION_AVAILABILITY", "DER_RESERVE_MAXIMUM_CHARGEDURATION_AVAILABILITY", "DER_READINGTIME_AVAILABILITY", "DER_CONTROL_MODE_TYPE_CAPABILITY", "DER_RESERVE_CHARGEPERCENT_AVAILABILITY", "DER_TYPE_CAPABILITY", "DER_RESERVE_PERCENT_AVAILABILITY", "DER_ABNORMAL_CATEGORY_TYPE_CAPABILITY", "DER_RESERVE_REACTIVEPOWER_AVAILABILITY_VAR", "DER_MAXIMUM_CURRENT_CAPABILITY_A", "DER_RESERVE_ACTIVEPOWER_AVAILABILITY_W", "DER_MAXIMUM_USEABLEENERGY_CAPABILITY_AH", "DER_NORMAL_CATEGORY_TYPE_CAPABILITY", "DER_MAXIMUM_CHARGERATE_APPARENTPOWER_CAPABILITY_VA", "DER_MAXIMUM_CHARGERATE_ACTIVEPOWER_CAPABILITY_W", "DER_MAXIMUM_DISCHARGERATE_APPARENTPOWER_CAPABILITY_VA", "DER_MAXIMUM_DISCHARGERATE_ACTIVEPOWER_CAPABILITY_W", "DER_MAXIMUM_VOLTAGE_CAPABILITY_V", "DER_MAXIMUM_APPARENTPOWER_CAPABILITY_VA", "DER_MAXIMUM_REACTIVEPOWER_CAPABILITY_VAR", "DER_MAXIMUM_REACTIVEPOWER_NEGATIVE_CAPABILITY_VARNEG", "DER_MAXIMUM_ACTIVEPOWER_CAPABILITY_W", "DER_MAXIMUM_ENERGYSTORAGE_CAPABILITY_WH", "DER_MINIMUM_OVEREXCITED_POWERFACTOR_CAPABILITY_PF", "DER_MINIMUM_UNDEREXCITED_POWERFACTOR_CAPABILITY_PF", "DER_MINIMUM_VOLTAGE_CAPABILITY_V", "DER_OVEREXCITED_POWERFACTOR_CAPABILITY_PF", "DER_OVEREXCITED_ACTIVEPOWER_CAPABILITY_W", "DER_REACTIVESUSCEPTANCE_CAPABILITY", "DER_UNDEREXCITED_POWERFACTOR_CAPABILITY_PF", "DER_UNDEREXCITED_ACTIVEPOWER_CAPABILITY_W", "DER_NOMINAL_VOLTAGE_CAPABILITY_V", "DER_CONTROL_MODE_TYPE_SETTINGS", "DER_ENTERSERVICE_DELAY_SETTINGS", "DER_ENTERSERVICE_FREQUENCY_HIGH_SETTINGS", "DER_ENTERSERVICE_FREQUENCY_LOW_SETTINGS", "DER_ENTERSERVICE_RAMPRATE_SETTINGS", "DER_ENTERSERVICE_RANDOM_DELAY_SETTINGS", "DER_ENTERSERVICE_VOLTAGE_HIGH_SETTINGS_V", "DER_ENTERSERVICE_VOLTAGE_LOW_SETTINGS_V", "DER_MAX_ACTIVEPOWER_RAMPRATE_SETTINGS_W", "DER_MAXIMUM_CURRENT_SETTINGS_A", "DER_MAXIMUM_USABLEENERGY_SETTINGS_AH", "DER_MAXIMUM_CHARGERATE_APPARENTPOWER_SETTINGS_VA", "DER_MAXIMUM_CHARGERATE_ACTIVEPOWER_SETTINGS_W", "DER_MAXIMUM_DISCHARGERATE_APPARENTPOWER_SETTINGS_VA", "DER_MAXIMUM_DISCHARGERATE_ACTIVEPOWER_SETTINGS_W", "DER_MAXIMUM_VOLTAGE_SETTINGS_V", "DER_MAXIMUM_APPARENTPOWER_SETTINGS_VA", "DER_MAXIMUM_REACTIVEPOWER_SETTINGS_VAR", "DER_MAXIMUM_REACTIVEPOWER_NEGATIVE_SETTINGS_VARNEG", "DER_MAXIMUM_ACTIVEPOWER_SETTINGS_W", "DER_MAXIMUM_ENERGYSTORAGE_SETTINGS_WH", "DER_MINIMUM_VOLTAGE_SETTINGS_V", "DER_OVEREXCITED_POWERFACTOR_SETTINGS_PF", "DER_UNDEREXCITED_POWERFACTOR_SETTINGS_PF", "DER_ACTIVEPOWER_SOFTSTART_RAMPRATE_SETTINGS_W", "UTILITY_NOMINAL_VOLTAGE_SETTINGS_V", "DER_UPDATED_TIME_SETTINGS", "DER_NOMINAL_VOLTAGE_SETTINGS_V", "DER_ALARM_TYPE_STATUS", "DER_CONNECTEDGENERATOR_TYPE_STATUS", "DER_CONNECTEDSTORAGE_TYPE_STATUS", "DER_INVERTER_TYPE_STATUS", "DER_LOCALCONTROLMODE_TYPE_STATUS", "DER_OPERATIONALMODE_TYPE_STATUS", "DER_STORAGEMODE_TYPE_STATUS", "DER_MANUFACTURER_STATUS_DATETIME", "DER_MANUFACTURER_STATUS_VALUE", "DER_STATEOFCHARGE_STATUS_DATETIME", "DER_STATEOFCHARGE_STATUS_VALUE", "DER_READINGTIME_STATUS"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_GRID_CIRCUIT_DISTRIBUTION" AS "ELECTRIC_GRID_CIRCUIT_DISTRIBUTION" KEY ("ELECTRIC_GRID_CIRCUIT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "ELECTRIC_GRID_CIRCUIT_ID", "ELECTRIC_SUBSTATION_ID"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_GRID_CIRCUIT_TRANSMISSION" AS "ELECTRIC_GRID_CIRCUIT_TRANSMISSION" KEY ("ELECTRIC_GRID_CIRCUIT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "ELECTRIC_GRID_CIRCUIT_ID", "ELECTRIC_SUBSTATION_ID"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_METER" AS "ELECTRIC_METER" KEY ("UTILITY_METER_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_METER_ID", "UTILITY_METER_BADGE_NUMBER", "UTILITY_METER_SERIAL_NUMBER"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_METER_INSTALLATION" AS "ELECTRIC_METER_INSTALLATION" KEY ("UTILITY_METER_INSTALLATION_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_METER_INSTALLATION_ID", "UTILITY_METER_ID", "UTILITY_SERVICE_POINT_ID", "END_DATE_TIME", "START_DATE_TIME"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_OUTAGE" AS "ELECTRIC_OUTAGE" KEY ("OUTAGE_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "OUTAGE_ID", "UTILITY_NAME", "UTILITY_ID", "UTILITY_NAMING_AUTHORITY", "ESTIMATED_RESTORATION_TIME_CONFIDENCE_KIND", "ESTIMATED_RESTORATION_TIME", "ESTIMATED_RESTORATION_TIME_SOURCE_KIND", "LOCATION_ZONE_KIND", "LOCATION_DIRECTION", "LOCATION_GEO_INFO_REFERENCE", "LOCATION_TYPE", "INCIDENT_CAUSE", "OUTAGE_AREA_KIND", "OUTAGE_AREA_EARLIEST_REPORTED_TIME", "OUTAGE_AREA_METERS_SERVED", "CREW_STATUS_KIND", "OUTAGE_CAUSE_KIND", "OUTAGE_COMMUNITY_DESCRIPTOR_STRING", "OUTAGE_COMMUNITY_DESCRIPTOR_COUNTY", "OUTAGE_PERIOD_ESTIMATED_END", "OUTAGE_PERIOD_ESTIMATED_START", "OUTAGE_PERIOD_ACTUAL_END", "OUTAGE_PERIOD_ACTUAL_START", "OUTAGE_REPORTED_STARTTIME", "OUTAGE_STATUS_KIND", "OUTAGE_CAUSE", "OUTAGE_CUSTOMERS_RESTORED", "OUTAGE_METERS_AFFECTED", "OUTAGE_ORIGINAL_CUSTOMERS_SERVED", "OUTAGE_ORIGINAL_METERS_AFFECTED", "OUTAGE_UTILITY_DISCLAIMER", "GEO_JSON", "LATITUDE", "LONGITUDE", "ALTITUDE"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_SERVICE_CONTRACT" AS "ELECTRIC_SERVICE_CONTRACT" KEY ("UTILITY_SERVICE_CONTRACT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_CONTRACT_ID", "UTILITY_ACCOUNT_ID", "START_DATE_TIME", "END_DATE_TIME", "UTILITY_DIVISION", "UTILITY_RATE_CODE", "RATE_CODE_EFFECTIVE_DATE", "SERVICE_CONTRACT_TYPE", "STATUS_CODE", "BILLING_SPECIALIZED_CONDITION", "SOLAR_BILLING_CADENCE"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_SERVICE_CONTRACTED_ITEM" AS "ELECTRIC_SERVICE_CONTRACTED_ITEM" KEY ("UTILITY_SERVICE_CONTRACTED_ITEM_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_CONTRACTED_ITEM_ID", "UTILITY_SERVICE_CONTRACT_ID", "UTILITY_SERVICE_POINT_ID", "START_DATE_TIME", "END_DATE_TIME", "USAGE_CALCULATION_OPERATION", "USAGE_CALCULATION_PERCENTAGE"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_SERVICE_POINT" AS "ELECTRIC_SERVICE_POINT" KEY ("UTILITY_SERVICE_POINT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_POINT_ID", "UTILITY_LOCATION_ID", "ACTUAL_START_DATE_TIME", "ACTUAL_END_DATE_TIME", "STATUS_CODE", "POSSESSES_SOLAR_PV", "POSSESSES_BATTERY_STORAGE_SYSTEM"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_SERVICE_POINT_GRID_CONNECTION" AS "ELECTRIC_SERVICE_POINT_GRID_CONNECTION" KEY ("UTILITY_SERVICE_POINT_ID","ELECTRIC_TRANSFORMER_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_POINT_ID", "ELECTRIC_TRANSFORMER_ID"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_SUBSTATION" AS "ELECTRIC_SUBSTATION" KEY ("ELECTRIC_SUBSTATION_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "ELECTRIC_SUBSTATION_ID", "ELECTRIC_SUBSTATION_NAME"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_TRANSFORMER_DISTRIBUTION" AS "ELECTRIC_TRANSFORMER_DISTRIBUTION" KEY ("ELECTRIC_TRANSFORMER_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "ELECTRIC_TRANSFORMER_ID", "ELECTRIC_GRID_CIRCUIT_ID", "STREET_ADDRESS", "CITY", "POSTAL_CODE", "ADDRESS_COUNTY", "ADDRESS_REGION_CODE", "COUNTRY_CODE", "STREET_ADDRESS_TYPE", "LATITUDE", "LONGITUDE"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_TRANSFORMER_DISTRIBUTION_MOBILE" AS "ELECTRIC_TRANSFORMER_DISTRIBUTION_MOBILE" KEY ("ELECTRIC_TRANSFORMER_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "ELECTRIC_TRANSFORMER_ID", "ELECTRIC_GRID_CIRCUIT_ID"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_TRANSFORMER_DISTRIBUTION_SERVICE" AS "ELECTRIC_TRANSFORMER_DISTRIBUTION_SERVICE" KEY ("ELECTRIC_TRANSFORMER_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "ELECTRIC_TRANSFORMER_ID", "ELECTRIC_GRID_CIRCUIT_ID", "STREET_ADDRESS", "CITY", "POSTAL_CODE", "ADDRESS_COUNTY", "ADDRESS_REGION_CODE", "COUNTRY_CODE", "STREET_ADDRESS_TYPE", "LATITUDE", "LONGITUDE"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_TRANSFORMER_POWER" AS "ELECTRIC_TRANSFORMER_POWER" KEY ("ELECTRIC_TRANSFORMER_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "ELECTRIC_TRANSFORMER_ID", "STREET_ADDRESS", "CITY", "POSTAL_CODE", "ADDRESS_COUNTY", "ADDRESS_REGION_CODE", "COUNTRY_CODE", "STREET_ADDRESS_TYPE", "LATITUDE", "LONGITUDE"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_TRANSFORMER_POWER_GSU" AS "ELECTRIC_TRANSFORMER_POWER_GSU" KEY ("ELECTRIC_TRANSFORMER_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "ELECTRIC_TRANSFORMER_ID", "STREET_ADDRESS", "CITY", "POSTAL_CODE", "ADDRESS_COUNTY", "ADDRESS_REGION_CODE", "COUNTRY_CODE", "STREET_ADDRESS_TYPE", "LATITUDE", "LONGITUDE"),
   "INDUSTRY_EW#MODEL"."ELECTRIC_TRANSFORMER_POWER_MOBILE" AS "ELECTRIC_TRANSFORMER_POWER_MOBILE" KEY ("ELECTRIC_TRANSFORMER_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "ELECTRIC_TRANSFORMER_ID"),
   "INDUSTRY_EW#MODEL"."EQUIPMENT_CONTAINER_CIM" AS "EQUIPMENT_CONTAINER_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME"),
   "INDUSTRY_EW#MODEL"."EV_CHARGING_LOCATION" AS "EV_CHARGING_LOCATION" KEY ("EV_CHARGING_LOCATION_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "EV_CHARGING_LOCATION_ID", "LATITUDE", "LONGITUDE", "EV_CHARGING_LOCATION_NAME", "EV_FACILITY_TYPE_DETAILS", "NAICS_CODE", "EV_CHARGING_NETWORK", "EV_CHARGING_NETWORK_WEBSITE", "STREET_ADDRESS", "CITY", "POSTAL_CODE", "ADDRESS_COUNTY", "ADDRESS_REGION_CODE", "COUNTRY_CODE", "PRIMARY_TELEPHONE_COUNTRY_CODE", "PRIMARY_TELEPHONE_NUMBER", "EV_CHARGING_LOCATION_STATUS", "LOCATION_ACCESS_DAYS_AND_TIMES", "CREDIT_CARDS_ACCEPTED", "COUNT_LEVEL_1_EV_CHARGERS", "COUNT_LEVEL_2_EV_CHARGERS", "COUNT_DC_FAST_EV_CHARGERS", "EV_CONNECTOR_TYPE_DETAILS", "EV_CHARGING_PRICING_DETAILS", "OPEN_DATE", "EV_ONSITE_RENEWABLE_SOURCE", "LOCATION_ACCESS_TYPE", "PHYSICAL_ACCESS_TYPE", "RESTRICTED_PHYSICAL_ACCESS_NOTES"),
   "INDUSTRY_EW#MODEL"."EV_DETECTION" AS "EV_DETECTION" KEY ("UTILITY_SERVICE_POINT_ID","DETECTION_START_DATE_TIME")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_POINT_ID", "DETECTION_START_DATE_TIME", "DETECTION_END_DATE_TIME", "STREET_ADDRESS", "CITY", "POSTAL_CODE", "ADDRESS_COUNTY", "ADDRESS_REGION_CODE", "COUNTRY_CODE", "CONFIDENCE_SCORE_AVERAGE", "CONFIDENCE_SCORE_MAXIMUM", "ALGORITHM_CONFIDENCE_THRESHOLD", "DAYS_ABOVE_CONFIDENCE_THRESHOLD"),
   "INDUSTRY_EW#MODEL"."EV_REGISTRATION_WITH_STATE" AS "EV_REGISTRATION_WITH_STATE" KEY ("VEHICLE_REGISTRATION_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "VEHICLE_REGISTRATION_ID", "CITY", "POSTAL_CODE", "ADDRESS_COUNTY", "ADDRESS_REGION_CODE", "COUNTRY_CODE", "VIN_ANONYMIZED", "EV_MAKE", "EV_MODEL_SERIES", "EV_MODEL_YEAR", "RELATED_ELECTRIC_UTILITY"),
   "INDUSTRY_EW#MODEL"."EV_SELF_REPORTED_POSSESSION" AS "EV_SELF_REPORTED_POSSESSION" KEY ("EMAIL","RECORDED_AT_DATE_TIME")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "EMAIL", "RECORDED_AT_DATE_TIME", "EV_SERIES_REPORTED", "EV_MODEL_REPORTED", "EV_CHARGER_TYPE_REPORTED", "YEARS_POSSESSING_EV", "DAYS_PER_WEEK_CHARGING_EV_AT_HOME", "MILES_DRIVEN_PER_DAY_EV", "NUMBER_OF_EVS_IN_POSSESSION"),
   "INDUSTRY_EW#MODEL"."FEEDER_CIM" AS "FEEDER_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME"),
   "INDUSTRY_EW#MODEL"."FUEL_GENERATOR_SELF_REPORTED_POSSESSION" AS "FUEL_GENERATOR_SELF_REPORTED_POSSESSION" KEY ("EMAIL","RECORDED_AT_DATE_TIME")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "EMAIL", "RECORDED_AT_DATE_TIME"),
   "INDUSTRY_EW#MODEL"."GAS_METER" AS "GAS_METER" KEY ("UTILITY_METER_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_METER_ID", "UTILITY_METER_BADGE_NUMBER", "UTILITY_METER_SERIAL_NUMBER"),
   "INDUSTRY_EW#MODEL"."GAS_METER_INSTALLATION" AS "GAS_METER_INSTALLATION" KEY ("UTILITY_METER_INSTALLATION_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_METER_INSTALLATION_ID", "UTILITY_METER_ID", "UTILITY_SERVICE_POINT_ID", "END_DATE_TIME", "START_DATE_TIME"),
   "INDUSTRY_EW#MODEL"."GAS_SERVICE_CONTRACT" AS "GAS_SERVICE_CONTRACT" KEY ("UTILITY_SERVICE_CONTRACT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_CONTRACT_ID", "UTILITY_ACCOUNT_ID", "START_DATE_TIME", "END_DATE_TIME", "UTILITY_DIVISION", "UTILITY_RATE_CODE", "RATE_CODE_EFFECTIVE_DATE", "SERVICE_CONTRACT_TYPE", "STATUS_CODE", "BILLING_SPECIALIZED_CONDITION"),
   "INDUSTRY_EW#MODEL"."GAS_SERVICE_CONTRACTED_ITEM" AS "GAS_SERVICE_CONTRACTED_ITEM" KEY ("UTILITY_SERVICE_CONTRACTED_ITEM_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_CONTRACTED_ITEM_ID", "UTILITY_SERVICE_CONTRACT_ID", "UTILITY_SERVICE_POINT_ID", "START_DATE_TIME", "END_DATE_TIME", "USAGE_CALCULATION_OPERATION", "USAGE_CALCULATION_PERCENTAGE"),
   "INDUSTRY_EW#MODEL"."GAS_SERVICE_POINT" AS "GAS_SERVICE_POINT" KEY ("UTILITY_SERVICE_POINT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_POINT_ID", "UTILITY_LOCATION_ID", "ACTUAL_START_DATE_TIME", "ACTUAL_END_DATE_TIME", "STATUS_CODE"),
   "INDUSTRY_EW#MODEL"."GEO_UNIT" AS "GEO_UNIT" KEY ("GEO_UNIT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "GEO_UNIT_ID", "GEO_UNIT_NAME", "COUNTRY", "LATITUDE", "LONGITUDE", "ALTITUDE", "GEO_JSON", "QUADKEY", "GEO_UNIT_TYPE", "GEO_UNIT_CUSTOM_TAGS", "DERIVATION_ORIGIN_ENTITY", "DERIVATION_ORIGIN_ENTITY_UUID"),
   "INDUSTRY_EW#MODEL"."HOUSEHOLD_APPLIANCE_DETECTION" AS "HOUSEHOLD_APPLIANCE_DETECTION" KEY ("UTILITY_ACCOUNT_ID","COMMODITY_TYPE","DISAGGREGATION_CATEGORY_TYPE","DETECTION_DATE_TIME")
   "INDUSTRY_EW#MODEL"."HOUSEHOLD_APPLIANCE_DISAGGREGATION" AS "HOUSEHOLD_APPLIANCE_DISAGGREGATION" KEY ("UTILITY_ACCOUNT_ID","COMMODITY_TYPE","DISAGGREGATION_CATEGORY_TYPE","PERIOD_START_DATE","PERIOD_END_DATE")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_ACCOUNT_ID", "COMMODITY_TYPE", "DISAGGREGATION_CATEGORY_TYPE", "PERIOD_START_DATE", "PERIOD_END_DATE", "RATIO"),
   "INDUSTRY_EW#MODEL"."INSTANCE_SET_NODE_CIM" AS "INSTANCE_SET_NODE_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME"),
   "INDUSTRY_EW#MODEL"."LOCATION_CIM" AS "LOCATION_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "COORDINATE_SYSTEM"),
   "INDUSTRY_EW#MODEL"."MEASUREMENT_EXCEPTION" AS "MEASUREMENT_EXCEPTION" KEY ("MEASUREMENT_EXCEPTION_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "MEASUREMENT_EXCEPTION_ID", "METER_CHANNEL_ID", "EXCEPTION_TYPE", "EXCEPTION_SEVERITY", "EXCEPTION_STATUS_TYPE", "VALIDATION_RULE_NAME", "VALIDATION_GROUP_NAME", "MEASUREMENT_START_DATE_TIME", "MEASUREMENT_END_DATE_TIME", "EXCEPTION_CREATION_DATE_TIME"),
   "INDUSTRY_EW#MODEL"."METER_CHANNEL" AS "METER_CHANNEL" KEY ("METER_CHANNEL_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "METER_CHANNEL_ID", "UTILITY_METER_ID", "METER_CONFIGURATION_ID", "COMMODITY_MEASUREMENT_TYPE", "METER_CHANNEL_TYPE"),
   "INDUSTRY_EW#MODEL"."METER_CONFIGURATION" AS "METER_CONFIGURATION" KEY ("METER_CONFIGURATION_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "METER_CONFIGURATION_ID", "START_DATE_TIME", "END_DATE_TIME", "UTILITY_SERVICE_TYPE", "UTILITY_METER_ID"),
   "INDUSTRY_EW#MODEL"."ORGANIZATION" AS "ORGANIZATION" KEY ("ORGANIZATION_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "ORGANIZATION_ID", "ORGANIZATION_NAME", "US_EMPLOYER_IDENTIFICATION_NUMBER", "PRIMARY_EMAIL", "PRIMARY_EMAIL_TYPE", "PRIMARY_TELEPHONE_COUNTRY_CODE", "PRIMARY_TELEPHONE_NUMBER", "PRIMARY_TELEPHONE_NUMBER_TYPE", "MAILING_STREET_ADDRESS", "MAILING_ADDRESS_CITY", "MAILING_ADDRESS_POSTAL_CODE", "MAILING_ADDRESS_COUNTY", "MAILING_ADDRESS_REGION_CODE", "MAILING_ADDRESS_COUNTRY_CODE", "MAILING_STREET_ADDRESS_TYPE", "STREET_ADDRESS", "CITY", "POSTAL_CODE", "ADDRESS_COUNTY", "ADDRESS_REGION_CODE", "COUNTRY_CODE", "STREET_ADDRESS_TYPE", "ECO_FRIENDLY_AFFINITY", "RESIDENCY_TYPE", "NAICS_CODE", "SIC_CODE", "POSSESSES_SOLAR_PV", "POSSESSES_ELECTRIC_VEHICLE"),
   "INDUSTRY_EW#MODEL"."PARTY" AS "PARTY" KEY ("PARTY_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "PARTY_ID", "PARTY_NAME", "PARTY_TYPE", "PERSON_ID", "ORGANIZATION_ID"),
   "INDUSTRY_EW#MODEL"."PERSON" AS "PERSON" KEY ("PERSON_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "PERSON_ID", "FIRST_NAME", "MIDDLE_NAME", "LAST_NAME", "NAME_PREFIX", "NAME_SUFFIX", "SSN", "DRIVER_LICENSE", "PRIMARY_EMAIL", "PRIMARY_EMAIL_TYPE", "LANGUAGE_PREFERENCE", "PRIMARY_TELEPHONE_COUNTRY_CODE", "PRIMARY_TELEPHONE_NUMBER", "PRIMARY_TELEPHONE_NUMBER_TYPE", "MAILING_STREET_ADDRESS", "MAILING_ADDRESS_CITY", "MAILING_ADDRESS_POSTAL_CODE", "MAILING_ADDRESS_COUNTY", "MAILING_ADDRESS_REGION_CODE", "MAILING_ADDRESS_COUNTRY_CODE", "MAILING_STREET_ADDRESS_TYPE", "HOME_STREET_ADDRESS", "HOME_ADDRESS_CITY", "HOME_ADDRESS_POSTAL_CODE", "HOME_ADDRESS_COUNTY", "HOME_ADDRESS_REGION_CODE", "HOME_ADDRESS_COUNTRY_CODE", "HOME_STREET_ADDRESS_TYPE", "BIRTH_DATE", "INCOME_RANGE_BOTTOM", "INCOME_RANGE_TOP", "NUMBER_OF_ADULTS_IN_HOUSEHOLD", "NUMBER_OF_CHILDREN_IN_HOUSEHOLD", "ECO_FRIENDLY_AFFINITY", "RESIDENCY_TYPE", "POSSESSES_SOLAR_PV", "POSSESSES_ELECTRIC_VEHICLE"),
   "INDUSTRY_EW#MODEL"."POSITION_POINT_CIM" AS "POSITION_POINT_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "SEQUENCE_NUMBER", "X_POSITION", "Y_POSITION", "LOCATION"),
   "INDUSTRY_EW#MODEL"."POWER_TRANSFORMER_CIM" AS "POWER_TRANSFORMER_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "DESCRIPTION", "VECTOR_GROUP", "EQUIPMENT_CONTAINER", "LOCATION"),
   "INDUSTRY_EW#MODEL"."SOLAR_ARRAY_SELF_REPORTED_POSSESSION" AS "SOLAR_ARRAY_SELF_REPORTED_POSSESSION" KEY ("EMAIL","RECORDED_AT_DATE_TIME")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "EMAIL", "RECORDED_AT_DATE_TIME"),
   "INDUSTRY_EW#MODEL"."SPECIALIZED_SERVICE_CONTRACT" AS "SPECIALIZED_SERVICE_CONTRACT" KEY ("UTILITY_SERVICE_CONTRACT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_CONTRACT_ID", "UTILITY_ACCOUNT_ID", "START_DATE_TIME", "END_DATE_TIME", "UTILITY_DIVISION", "SPECIAL_PURPOSE_TYPE"),
   "INDUSTRY_EW#MODEL"."SUBSTATION_CIM" AS "SUBSTATION_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "NORMAL_ENERGIZED_FEEDER"),
   "INDUSTRY_EW#MODEL"."SWITCH_CIM" AS "SWITCH_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME"),
   "INDUSTRY_EW#MODEL"."SWITCH_PHASE_CIM" AS "SWITCH_PHASE_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "NORMAL_OPEN", "RATED_CURRENT", "SWITCH", "PHASE_SIDE_1", "PHASE_SIDE_2"),
   "INDUSTRY_EW#MODEL"."TERMINAL_CIM" AS "TERMINAL_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "SEQUENCE_NUMBER", "CONDUCTING_EQUIPMENT", "CONNECTIVITY_NODE"),
   "INDUSTRY_EW#MODEL"."TRANSFORMER_END_INFO_CIM" AS "TRANSFORMER_END_INFO_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "DESCRIPTION", "EMERGENCY_S", "END_NUMBER", "INSULATION", "PHASE_ANGLE_CLOCK", "R", "RATED_S", "RATED_U", "SHORT_TERM_S", "TRANSFORMER_TANK_INFO", "CONNECTION_KIND"),
   "INDUSTRY_EW#MODEL"."TRANSFORMER_TANK_CIM" AS "TRANSFORMER_TANK_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "POWER_TRANSFORMER", "TRANSFORMER_TANK_INFO"),
   "INDUSTRY_EW#MODEL"."TRANSFORMER_TANK_END_CIM" AS "TRANSFORMER_TANK_END_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "GROUNDED", "END_NUMBER", "R_GROUND", "X_GROUND", "BASE_VOLTAGE", "TERMINAL", "TRANSFORMER_TANK", "ORDERED_PHASES"),
   "INDUSTRY_EW#MODEL"."TRANSFORMER_TANK_INFO_NODE_CIM" AS "TRANSFORMER_TANK_INFO_NODE_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "DESCRIPTION"),
   "INDUSTRY_EW#MODEL"."UTILITY_ACCOUNT" AS "UTILITY_ACCOUNT" KEY ("UTILITY_ACCOUNT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_ACCOUNT_ID", "ACTUAL_START_DATE_TIME", "UTILITY_ACCOUNT_CLASS", "BILL_CYCLE", "DIVISION", "PARTY_ID"),
   "INDUSTRY_EW#MODEL"."UTILITY_ACCOUNT_INTERACTION_INSIGHTS" AS "UTILITY_ACCOUNT_INTERACTION_INSIGHTS" KEY ("UTILITY_ACCOUNT_ID","CREATION_DATE_TIME")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_ACCOUNT_ID", "CREATION_DATE_TIME", "CUSTOMER_SENTIMENT_PROJECTION", "CUSTOMER_INTERACTIONS_SUMMARY", "CUSTOMER_CONCERNS", "CUSTOMER_SPECIAL_CONSIDERATIONS", "CUSTOMER_OWNED_DEVICES"),
   "INDUSTRY_EW#MODEL"."UTILITY_BILL" AS "UTILITY_BILL" KEY ("UTILITY_BILL_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_BILL_ID", "UTILITY_ACCOUNT_ID", "BILL_DATE", "DUE_DATE", "CURRENCY", "ACCOUNT_CURRENT_BALANCE_AMOUNT", "ACCOUNT_PAYOFF_BALANCE_AMOUNT", "ACCOUNT_PREVIOUS_PERIOD_BALANCE_AMOUNT", "TOTAL_PAYMENTS_AMOUNT", "TOTAL_ADJUSTMENTS_AMOUNT", "TOTAL_BILL_CORRECTIONS_AMOUNT", "TOTAL_CURRENT_CHARGES_AMOUNT", "TOTAL_BALANCE_CURRENT_PERIOD_AMOUNT"),
   "INDUSTRY_EW#MODEL"."UTILITY_BILL_SERVICE_LINE_ITEM" AS "UTILITY_BILL_SERVICE_LINE_ITEM" KEY ("UTILITY_BILL_ID","UTILITY_SERVICE_SUMMARY_ID","UTILITY_SERVICE_PERIOD_ID","UTILITY_BILL_SERVICE_LINE_SEQUENCE")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_BILL_ID", "UTILITY_SERVICE_SUMMARY_ID", "UTILITY_SERVICE_PERIOD_ID", "UTILITY_BILL_SERVICE_LINE_SEQUENCE", "CALCULATED_AMOUNT", "DESCRIPTION_ON_BILL", "PRINT_LINE", "UTILITY_BILL_LINE_TYPE", "COMMODITY_MEASUREMENT_TYPE", "UNIT_OF_MEASURE", "TIME_OF_USE", "BILL_CALCULATION_EXTENSION", "USAGE_AMOUNT", "CALCULATION_BASIS_AMOUNT", "EXEMPT_AMOUNT", "MEASURES_PEAK_QUANTITY", "CURRENCY"),
   "INDUSTRY_EW#MODEL"."UTILITY_BILL_SERVICE_PERIOD" AS "UTILITY_BILL_SERVICE_PERIOD" KEY ("UTILITY_BILL_ID","UTILITY_SERVICE_SUMMARY_ID","UTILITY_SERVICE_PERIOD_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_BILL_ID", "UTILITY_SERVICE_SUMMARY_ID", "UTILITY_SERVICE_PERIOD_ID", "START_DATE", "END_DATE", "UTILITY_RATE_CODE", "UTILITY_RATE_EFFECTIVE_DATE", "DESCRIPTION_ON_BILL"),
   "INDUSTRY_EW#MODEL"."UTILITY_BILL_SERVICE_SUMMARY" AS "UTILITY_BILL_SERVICE_SUMMARY" KEY ("UTILITY_BILL_ID","UTILITY_SERVICE_SUMMARY_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_BILL_ID", "UTILITY_SERVICE_SUMMARY_ID", "UTILITY_SERVICE_CONTRACT_ID", "UTILITY_LOCATION_ID", "START_DATE", "END_DATE", "USAGE_PERIOD_START_DATE", "USAGE_PERIOD_END_DATE", "ESTIMATED_SERVICE_QUANTITIES", "SERVICE_CONTRACT_ENDING", "UTILITY_SERVICE_SUMMARY_STATUS", "UTILITY_BILL_CYCLE_CODE", "TOTAL_AMOUNT", "SERVICE_CONTRACT_CURRENT_BALANCE_AMOUNT"),
   "INDUSTRY_EW#MODEL"."UTILITY_BILL_SERVICE_USAGE" AS "UTILITY_BILL_SERVICE_USAGE" KEY ("UTILITY_BILL_ID","UTILITY_SERVICE_SUMMARY_ID","COMMODITY_MEASUREMENT_TYPE","UNIT_OF_MEASURE","TIME_OF_USE","BILL_CALCULATION_EXTENSION")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_BILL_ID", "UTILITY_SERVICE_SUMMARY_ID", "COMMODITY_MEASUREMENT_TYPE", "UNIT_OF_MEASURE", "TIME_OF_USE", "BILL_CALCULATION_EXTENSION", "START_DATE_TIME", "END_DATE_TIME", "USAGE_AMOUNT"),
   "INDUSTRY_EW#MODEL"."UTILITY_BILL_USAGE_DISAGGREGATION" AS "UTILITY_BILL_USAGE_DISAGGREGATION" KEY ("UTILITY_ACCOUNT_ID","COMMODITY_TYPE","DISAGGREGATION_CATEGORY_TYPE","BILL_PERIOD_START_DATE","BILL_PERIOD_END_DATE")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_ACCOUNT_ID", "COMMODITY_TYPE", "DISAGGREGATION_CATEGORY_TYPE", "BILL_PERIOD_START_DATE", "BILL_PERIOD_END_DATE", "RATIO", "UNIT_OF_MEASURE", "CURRENCY", "USAGE_AMOUNT", "COST_AMOUNT"),
   "INDUSTRY_EW#MODEL"."UTILITY_LOCATION" AS "UTILITY_LOCATION" KEY ("UTILITY_LOCATION_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_LOCATION_ID", "PARENT_UTILITY_LOCATION_ID", "UTILITY_LOCATION_TYPE", "STREET_ADDRESS", "CITY", "POSTAL_CODE", "ADDRESS_COUNTY", "ADDRESS_REGION_CODE", "COUNTRY_CODE", "STREET_ADDRESS_TYPE", "LATITUDE", "LONGITUDE"),
   "INDUSTRY_EW#MODEL"."VOLTAGE_LEVEL_CIM" AS "VOLTAGE_LEVEL_CIM" KEY ("CIM_URN_UUID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "CIM_URN_UUID", "NAME", "BASE_VOLTAGE", "SUBSTATION"),
   "INDUSTRY_EW#MODEL"."WASTEWATER_SERVICE_CONTRACT" AS "WASTEWATER_SERVICE_CONTRACT" KEY ("UTILITY_SERVICE_CONTRACT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_CONTRACT_ID", "UTILITY_ACCOUNT_ID", "START_DATE_TIME", "END_DATE_TIME", "UTILITY_DIVISION", "UTILITY_RATE_CODE"),
   "INDUSTRY_EW#MODEL"."WASTEWATER_SERVICE_CONTRACTED_ITEM" AS "WASTEWATER_SERVICE_CONTRACTED_ITEM" KEY ("UTILITY_SERVICE_CONTRACTED_ITEM_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_CONTRACTED_ITEM_ID", "UTILITY_SERVICE_CONTRACT_ID", "UTILITY_SERVICE_POINT_ID", "START_DATE_TIME", "END_DATE_TIME", "USAGE_CALCULATION_OPERATION", "USAGE_CALCULATION_PERCENTAGE"),
   "INDUSTRY_EW#MODEL"."WASTEWATER_SERVICE_POINT" AS "WASTEWATER_SERVICE_POINT" KEY ("UTILITY_SERVICE_POINT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_POINT_ID", "UTILITY_LOCATION_ID", "ACTUAL_START_DATE_TIME", "ACTUAL_END_DATE_TIME", "STATUS_CODE"),
   "INDUSTRY_EW#MODEL"."WATER_METER" AS "WATER_METER" KEY ("UTILITY_METER_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_METER_ID", "UTILITY_METER_BADGE_NUMBER", "UTILITY_METER_SERIAL_NUMBER"),
   "INDUSTRY_EW#MODEL"."WATER_METER_INSTALLATION" AS "WATER_METER_INSTALLATION" KEY ("UTILITY_METER_INSTALLATION_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_METER_INSTALLATION_ID", "UTILITY_METER_ID", "UTILITY_SERVICE_POINT_ID", "END_DATE_TIME", "START_DATE_TIME"),
   "INDUSTRY_EW#MODEL"."WATER_SERVICE_CONTRACT" AS "WATER_SERVICE_CONTRACT" KEY ("UTILITY_SERVICE_CONTRACT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_CONTRACT_ID", "UTILITY_ACCOUNT_ID", "START_DATE_TIME", "END_DATE_TIME", "UTILITY_DIVISION", "UTILITY_RATE_CODE", "RATE_CODE_EFFECTIVE_DATE", "SERVICE_CONTRACT_TYPE", "STATUS_CODE", "BILLING_SPECIALIZED_CONDITION"),
   "INDUSTRY_EW#MODEL"."WATER_SERVICE_CONTRACTED_ITEM" AS "WATER_SERVICE_CONTRACTED_ITEM" KEY ("UTILITY_SERVICE_CONTRACTED_ITEM_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_CONTRACTED_ITEM_ID", "UTILITY_SERVICE_CONTRACT_ID", "UTILITY_SERVICE_POINT_ID", "START_DATE_TIME", "END_DATE_TIME", "USAGE_CALCULATION_OPERATION", "USAGE_CALCULATION_PERCENTAGE"),
   "INDUSTRY_EW#MODEL"."WATER_SERVICE_POINT" AS "WATER_SERVICE_POINT" KEY ("UTILITY_SERVICE_POINT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "UTILITY_SERVICE_POINT_ID", "UTILITY_LOCATION_ID", "ACTUAL_START_DATE_TIME", "ACTUAL_END_DATE_TIME", "STATUS_CODE"),
   "INDUSTRY_EW#MODEL"."WEATHER_MEASUREMENT" AS "WEATHER_MEASUREMENT" KEY ("MEASUREMENT_ID")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "MEASUREMENT_ID", "LATITUDE", "LONGITUDE", "ALTITUDE", "QUADKEY", "END_TIMESTAMP", "START_TIMESTAMP", "INTERVAL_TYPE", "ACCURACY_CATEGORY", "OBSERVATION_CATEGORY", "MODEL_TYPE", "WEATHER_CODE", "COUNTRY_CODE", "RELATIVE_ELEVATION", "ASPECT", "UNIT_OF_MEASURE", "MEASUREMENT_VALUE"),
   "INDUSTRY_EW#MODEL"."WIND_TURBINE_SELF_REPORTED_POSSESSION" AS "WIND_TURBINE_SELF_REPORTED_POSSESSION" KEY ("EMAIL","RECORDED_AT_DATE_TIME")
      PROPERTIES ("SOURCE_UUID", "RECORD_UUID", "RECORD_LAST_CHANGE_TIMESTAMP", "EMAIL", "RECORDED_AT_DATE_TIME") )
  EDGE TABLES (
   "INDUSTRY_EW#MODEL"."BREAKER_CIM" AS "BREAKER_CIM_HASEQUIPMENT_ADDITIONALEQUIPMENTCONTAINER" KEY ("ADDITIONAL_EQUIPMENT_CONTAINER")
      SOURCE KEY("ADDITIONAL_EQUIPMENT_CONTAINER") REFERENCES BREAKER_CIM ("ADDITIONAL_EQUIPMENT_CONTAINER")
      DESTINATION KEY("ADDITIONAL_EQUIPMENT_CONTAINER") REFERENCES EQUIPMENT_CONTAINER_CIM ("CIM_URN_UUID")
     LABEL HASEQUIPMENT_ADDITIONALEQUIPMENTCONTAINER NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."BREAKER_CIM" AS "BREAKER_CIM_HASEQUIPMENT_EQUIPMENTCONTAINER" KEY ("EQUIPMENT_CONTAINER")
      SOURCE KEY("EQUIPMENT_CONTAINER") REFERENCES BREAKER_CIM ("EQUIPMENT_CONTAINER")
      DESTINATION KEY("EQUIPMENT_CONTAINER") REFERENCES EQUIPMENT_CONTAINER_CIM ("CIM_URN_UUID")
     LABEL HASEQUIPMENT_EQUIPMENTCONTAINER NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."BREAKER_CIM" AS "BREAKER_CIM_HASPOWERSYSTEMRESOURCE_LOCATION" KEY ("LOCATION")
      SOURCE KEY("LOCATION") REFERENCES BREAKER_CIM ("LOCATION")
      DESTINATION KEY("LOCATION") REFERENCES LOCATION_CIM ("CIM_URN_UUID")
     LABEL HASPOWERSYSTEMRESOURCE_LOCATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."BUSBAR_SET_CIM" AS "BUSBAR_SET_CIM_HASEQUIPMENT_EQUIPMENTCONTAINER" KEY ("EQUIPMENT_CONTAINER")
      SOURCE KEY("EQUIPMENT_CONTAINER") REFERENCES BUSBAR_SET_CIM ("EQUIPMENT_CONTAINER")
      DESTINATION KEY("EQUIPMENT_CONTAINER") REFERENCES EQUIPMENT_CONTAINER_CIM ("CIM_URN_UUID")
     LABEL HASEQUIPMENT_EQUIPMENTCONTAINER NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."CONTACT_CENTER_CUSTOMER_CALL" AS "CONTACT_CENTER_CUSTOMER_CALL_HASPARTY" KEY ("PARTY_ID")
      SOURCE KEY("PARTY_ID") REFERENCES CONTACT_CENTER_CUSTOMER_CALL ("PARTY_ID")
      DESTINATION KEY("PARTY_ID") REFERENCES PARTY ("PARTY_ID")
     LABEL HASPARTY NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."CONTACT_CENTER_CUSTOMER_CALL" AS "CONTACT_CENTER_CUSTOMER_CALL_HASUTILITYACCOUNT" KEY ("UTILITY_ACCOUNT_ID")
      SOURCE KEY("UTILITY_ACCOUNT_ID") REFERENCES CONTACT_CENTER_CUSTOMER_CALL ("UTILITY_ACCOUNT_ID")
      DESTINATION KEY("UTILITY_ACCOUNT_ID") REFERENCES UTILITY_ACCOUNT ("UTILITY_ACCOUNT_ID")
     LABEL HASUTILITYACCOUNT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."CONTACT_CENTER_CUSTOMER_CALL" AS "CONTACT_CENTER_CUSTOMER_CALL_HASUTILITYLOCATION" KEY ("UTILITY_LOCATION_ID")
      SOURCE KEY("UTILITY_LOCATION_ID") REFERENCES CONTACT_CENTER_CUSTOMER_CALL ("UTILITY_LOCATION_ID")
      DESTINATION KEY("UTILITY_LOCATION_ID") REFERENCES UTILITY_LOCATION ("UTILITY_LOCATION_ID")
     LABEL HASUTILITYLOCATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."CORE#GEO_UNIT_HIERARCHY" AS "CORE#GEO_UNIT_HIERARCHY_CONTAINSGEOUNIT" KEY ("GEO_UNIT_ID","CONTAINS_GEO_UNIT_ID")
      SOURCE KEY("CONTAINS_GEO_UNIT_ID") REFERENCES CORE#GEO_UNIT_HIERARCHY ("CONTAINS_GEO_UNIT_ID")
      DESTINATION KEY("CONTAINS_GEO_UNIT_ID") REFERENCES GEO_UNIT ("GEO_UNIT_ID")
     LABEL CONTAINSGEOUNIT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."DATA_PRODUCT" AS "DATA_PRODUCT_HASDATAPRODUCTOWNER" KEY ("DATA_OWNER_ID")
      SOURCE KEY("DATA_OWNER_ID") REFERENCES DATA_PRODUCT ("DATA_OWNER_ID")
      DESTINATION KEY("DATA_OWNER_ID") REFERENCES DATA_PRODUCT_OWNER ("DATA_OWNER_ID")
     LABEL HASDATAPRODUCTOWNER NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_GRID_CIRCUIT_DISTRIBUTION" AS "ELECTRIC_GRID_CIRCUIT_DISTRIBUTION_ISFEDBYELECTRICSUBSTATION" KEY ("ELECTRIC_SUBSTATION_ID")
      SOURCE KEY("ELECTRIC_SUBSTATION_ID") REFERENCES ELECTRIC_GRID_CIRCUIT_DISTRIBUTION ("ELECTRIC_SUBSTATION_ID")
      DESTINATION KEY("ELECTRIC_SUBSTATION_ID") REFERENCES ELECTRIC_SUBSTATION ("ELECTRIC_SUBSTATION_ID")
     LABEL ISFEDBYELECTRICSUBSTATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_GRID_CIRCUIT_TRANSMISSION" AS "ELECTRIC_GRID_CIRCUIT_TRANSMISSION_ISFEDBYELECTRICSUBSTATION" KEY ("ELECTRIC_SUBSTATION_ID")
      SOURCE KEY("ELECTRIC_SUBSTATION_ID") REFERENCES ELECTRIC_GRID_CIRCUIT_TRANSMISSION ("ELECTRIC_SUBSTATION_ID")
      DESTINATION KEY("ELECTRIC_SUBSTATION_ID") REFERENCES ELECTRIC_SUBSTATION ("ELECTRIC_SUBSTATION_ID")
     LABEL ISFEDBYELECTRICSUBSTATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_METER_INSTALLATION" AS "ELECTRIC_METER_INSTALLATION_HASCOMMODITYMETER" KEY ("UTILITY_METER_ID")
      SOURCE KEY("UTILITY_METER_ID") REFERENCES ELECTRIC_METER_INSTALLATION ("UTILITY_METER_ID")
      DESTINATION KEY("UTILITY_METER_ID") REFERENCES ELECTRIC_METER ("UTILITY_METER_ID")
     LABEL HASCOMMODITYMETER NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_METER_INSTALLATION" AS "ELECTRIC_METER_INSTALLATION_HASSERVICEPOINT" KEY ("UTILITY_SERVICE_POINT_ID")
      SOURCE KEY("UTILITY_SERVICE_POINT_ID") REFERENCES ELECTRIC_METER_INSTALLATION ("UTILITY_SERVICE_POINT_ID")
      DESTINATION KEY("UTILITY_SERVICE_POINT_ID") REFERENCES ELECTRIC_SERVICE_POINT ("UTILITY_SERVICE_POINT_ID")
     LABEL HASSERVICEPOINT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_SERVICE_CONTRACTED_ITEM" AS "ELECTRIC_SERVICE_CONTRACTED_ITEM_HASSERVICEPOINT" KEY ("UTILITY_SERVICE_POINT_ID")
      SOURCE KEY("UTILITY_SERVICE_POINT_ID") REFERENCES ELECTRIC_SERVICE_CONTRACTED_ITEM ("UTILITY_SERVICE_POINT_ID")
      DESTINATION KEY("UTILITY_SERVICE_POINT_ID") REFERENCES ELECTRIC_SERVICE_POINT ("UTILITY_SERVICE_POINT_ID")
     LABEL HASSERVICEPOINT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_SERVICE_CONTRACTED_ITEM" AS "ELECTRIC_SERVICE_CONTRACTED_ITEM_HASUTILITYSERVICECONTRACT" KEY ("UTILITY_SERVICE_CONTRACT_ID")
      SOURCE KEY("UTILITY_SERVICE_CONTRACT_ID") REFERENCES ELECTRIC_SERVICE_CONTRACTED_ITEM ("UTILITY_SERVICE_CONTRACT_ID")
      DESTINATION KEY("UTILITY_SERVICE_CONTRACT_ID") REFERENCES ELECTRIC_SERVICE_CONTRACT ("UTILITY_SERVICE_CONTRACT_ID")
     LABEL HASUTILITYSERVICECONTRACT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_SERVICE_CONTRACT" AS "ELECTRIC_SERVICE_CONTRACT_HASUTILITYACCOUNT" KEY ("UTILITY_ACCOUNT_ID")
      SOURCE KEY("UTILITY_ACCOUNT_ID") REFERENCES ELECTRIC_SERVICE_CONTRACT ("UTILITY_ACCOUNT_ID")
      DESTINATION KEY("UTILITY_ACCOUNT_ID") REFERENCES UTILITY_ACCOUNT ("UTILITY_ACCOUNT_ID")
     LABEL HASUTILITYACCOUNT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_SERVICE_POINT_GRID_CONNECTION" AS "ELECTRIC_SERVICE_POINT_GRID_CONNECTION_FEEDSELECTRICSERVICEPOINT" KEY ("UTILITY_SERVICE_POINT_ID")
      SOURCE KEY("UTILITY_SERVICE_POINT_ID") REFERENCES ELECTRIC_SERVICE_POINT_GRID_CONNECTION ("UTILITY_SERVICE_POINT_ID")
      DESTINATION KEY("UTILITY_SERVICE_POINT_ID") REFERENCES ELECTRIC_SERVICE_POINT ("UTILITY_SERVICE_POINT_ID")
     LABEL FEEDSELECTRICSERVICEPOINT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_SERVICE_POINT_GRID_CONNECTION" AS "ELECTRIC_SERVICE_POINT_GRID_CONNECTION_ISFEDBYELECTRICSERVICETRANSFORMER" KEY ("ELECTRIC_TRANSFORMER_ID")
      SOURCE KEY("ELECTRIC_TRANSFORMER_ID") REFERENCES ELECTRIC_SERVICE_POINT_GRID_CONNECTION ("ELECTRIC_TRANSFORMER_ID")
      DESTINATION KEY("ELECTRIC_TRANSFORMER_ID") REFERENCES ELECTRIC_TRANSFORMER_DISTRIBUTION_SERVICE ("ELECTRIC_TRANSFORMER_ID")
     LABEL ISFEDBYELECTRICSERVICETRANSFORMER NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_SERVICE_POINT" AS "ELECTRIC_SERVICE_POINT_HASUTILITYLOCATION" KEY ("UTILITY_LOCATION_ID")
      SOURCE KEY("UTILITY_LOCATION_ID") REFERENCES ELECTRIC_SERVICE_POINT ("UTILITY_LOCATION_ID")
      DESTINATION KEY("UTILITY_LOCATION_ID") REFERENCES UTILITY_LOCATION ("UTILITY_LOCATION_ID")
     LABEL HASUTILITYLOCATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_TRANSFORMER_DISTRIBUTION" AS "ELECTRIC_TRANSFORMER_DISTRIBUTION_ISFEDBYELECTRICGRIDCIRCUIT" KEY ("ELECTRIC_GRID_CIRCUIT_ID")
      SOURCE KEY("ELECTRIC_GRID_CIRCUIT_ID") REFERENCES ELECTRIC_TRANSFORMER_DISTRIBUTION ("ELECTRIC_GRID_CIRCUIT_ID")
      DESTINATION KEY("ELECTRIC_GRID_CIRCUIT_ID") REFERENCES ELECTRIC_GRID_CIRCUIT_DISTRIBUTION ("ELECTRIC_GRID_CIRCUIT_ID")
     LABEL ISFEDBYELECTRICGRIDCIRCUIT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_TRANSFORMER_DISTRIBUTION_MOBILE" AS "ELECTRIC_TRANSFORMER_DISTRIBUTION_MOBILE_ISFEDBYELECTRICGRIDCIRCUIT" KEY ("ELECTRIC_GRID_CIRCUIT_ID")
      SOURCE KEY("ELECTRIC_GRID_CIRCUIT_ID") REFERENCES ELECTRIC_TRANSFORMER_DISTRIBUTION_MOBILE ("ELECTRIC_GRID_CIRCUIT_ID")
      DESTINATION KEY("ELECTRIC_GRID_CIRCUIT_ID") REFERENCES ELECTRIC_GRID_CIRCUIT_DISTRIBUTION ("ELECTRIC_GRID_CIRCUIT_ID")
     LABEL ISFEDBYELECTRICGRIDCIRCUIT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."ELECTRIC_TRANSFORMER_DISTRIBUTION_SERVICE" AS "ELECTRIC_TRANSFORMER_DISTRIBUTION_SERVICE_ISFEDBYELECTRICGRIDCIRCUIT" KEY ("ELECTRIC_GRID_CIRCUIT_ID")
      SOURCE KEY("ELECTRIC_GRID_CIRCUIT_ID") REFERENCES ELECTRIC_TRANSFORMER_DISTRIBUTION_SERVICE ("ELECTRIC_GRID_CIRCUIT_ID")
      DESTINATION KEY("ELECTRIC_GRID_CIRCUIT_ID") REFERENCES ELECTRIC_GRID_CIRCUIT_DISTRIBUTION ("ELECTRIC_GRID_CIRCUIT_ID")
     LABEL ISFEDBYELECTRICGRIDCIRCUIT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."EV_DETECTION" AS "EV_DETECTION_HASSERVICEPOINT" KEY ("UTILITY_SERVICE_POINT_ID")
      SOURCE KEY("UTILITY_SERVICE_POINT_ID") REFERENCES EV_DETECTION ("UTILITY_SERVICE_POINT_ID")
      DESTINATION KEY("UTILITY_SERVICE_POINT_ID") REFERENCES ELECTRIC_SERVICE_POINT ("UTILITY_SERVICE_POINT_ID")
     LABEL HASSERVICEPOINT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."EV_REGISTRATION_WITH_STATE" AS "EV_REGISTRATION_WITH_STATE_HASUTILITY" KEY ("RELATED_ELECTRIC_UTILITY")
      SOURCE KEY("RELATED_ELECTRIC_UTILITY") REFERENCES EV_REGISTRATION_WITH_STATE ("RELATED_ELECTRIC_UTILITY")
      DESTINATION KEY("RELATED_ELECTRIC_UTILITY") REFERENCES ORGANIZATION ("ORGANIZATION_ID")
     LABEL HASUTILITY NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."GAS_METER_INSTALLATION" AS "GAS_METER_INSTALLATION_HASCOMMODITYMETER" KEY ("UTILITY_METER_ID")
      SOURCE KEY("UTILITY_METER_ID") REFERENCES GAS_METER_INSTALLATION ("UTILITY_METER_ID")
      DESTINATION KEY("UTILITY_METER_ID") REFERENCES GAS_METER ("UTILITY_METER_ID")
     LABEL HASCOMMODITYMETER NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."GAS_METER_INSTALLATION" AS "GAS_METER_INSTALLATION_HASSERVICEPOINT" KEY ("UTILITY_SERVICE_POINT_ID")
      SOURCE KEY("UTILITY_SERVICE_POINT_ID") REFERENCES GAS_METER_INSTALLATION ("UTILITY_SERVICE_POINT_ID")
      DESTINATION KEY("UTILITY_SERVICE_POINT_ID") REFERENCES GAS_SERVICE_POINT ("UTILITY_SERVICE_POINT_ID")
     LABEL HASSERVICEPOINT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."GAS_SERVICE_CONTRACTED_ITEM" AS "GAS_SERVICE_CONTRACTED_ITEM_HASSERVICEPOINT" KEY ("UTILITY_SERVICE_POINT_ID")
      SOURCE KEY("UTILITY_SERVICE_POINT_ID") REFERENCES GAS_SERVICE_CONTRACTED_ITEM ("UTILITY_SERVICE_POINT_ID")
      DESTINATION KEY("UTILITY_SERVICE_POINT_ID") REFERENCES GAS_SERVICE_POINT ("UTILITY_SERVICE_POINT_ID")
     LABEL HASSERVICEPOINT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."GAS_SERVICE_CONTRACTED_ITEM" AS "GAS_SERVICE_CONTRACTED_ITEM_HASUTILITYSERVICECONTRACT" KEY ("UTILITY_SERVICE_CONTRACT_ID")
      SOURCE KEY("UTILITY_SERVICE_CONTRACT_ID") REFERENCES GAS_SERVICE_CONTRACTED_ITEM ("UTILITY_SERVICE_CONTRACT_ID")
      DESTINATION KEY("UTILITY_SERVICE_CONTRACT_ID") REFERENCES GAS_SERVICE_CONTRACT ("UTILITY_SERVICE_CONTRACT_ID")
     LABEL HASUTILITYSERVICECONTRACT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."GAS_SERVICE_CONTRACT" AS "GAS_SERVICE_CONTRACT_HASUTILITYACCOUNT" KEY ("UTILITY_ACCOUNT_ID")
      SOURCE KEY("UTILITY_ACCOUNT_ID") REFERENCES GAS_SERVICE_CONTRACT ("UTILITY_ACCOUNT_ID")
      DESTINATION KEY("UTILITY_ACCOUNT_ID") REFERENCES UTILITY_ACCOUNT ("UTILITY_ACCOUNT_ID")
     LABEL HASUTILITYACCOUNT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."GAS_SERVICE_POINT" AS "GAS_SERVICE_POINT_HASUTILITYLOCATION" KEY ("UTILITY_LOCATION_ID")
      SOURCE KEY("UTILITY_LOCATION_ID") REFERENCES GAS_SERVICE_POINT ("UTILITY_LOCATION_ID")
      DESTINATION KEY("UTILITY_LOCATION_ID") REFERENCES UTILITY_LOCATION ("UTILITY_LOCATION_ID")
     LABEL HASUTILITYLOCATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."GEO_UNIT" AS "GEO_UNIT_CONTAINSGEOUNIT" KEY ("GEO_UNIT_ID")
      SOURCE KEY("GEO_UNIT_ID") REFERENCES GEO_UNIT ("GEO_UNIT_ID")
      DESTINATION KEY("GEO_UNIT_ID") REFERENCES CORE#GEO_UNIT_HIERARCHY ("GEO_UNIT_ID")
     LABEL CONTAINSGEOUNIT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."HOUSEHOLD_APPLIANCE_DETECTION" AS "HOUSEHOLD_APPLIANCE_DETECTION_HASUTILITYACCOUNT" KEY ("UTILITY_ACCOUNT_ID")
      SOURCE KEY("UTILITY_ACCOUNT_ID") REFERENCES HOUSEHOLD_APPLIANCE_DETECTION ("UTILITY_ACCOUNT_ID")
      DESTINATION KEY("UTILITY_ACCOUNT_ID") REFERENCES UTILITY_ACCOUNT ("UTILITY_ACCOUNT_ID")
     LABEL HASUTILITYACCOUNT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."HOUSEHOLD_APPLIANCE_DISAGGREGATION" AS "HOUSEHOLD_APPLIANCE_DISAGGREGATION_HASUTILITYACCOUNT" KEY ("UTILITY_ACCOUNT_ID")
      SOURCE KEY("UTILITY_ACCOUNT_ID") REFERENCES HOUSEHOLD_APPLIANCE_DISAGGREGATION ("UTILITY_ACCOUNT_ID")
      DESTINATION KEY("UTILITY_ACCOUNT_ID") REFERENCES UTILITY_ACCOUNT ("UTILITY_ACCOUNT_ID")
     LABEL HASUTILITYACCOUNT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."LOCATION_CIM" AS "LOCATION_CIM_HASLOCATION_COORDINATESYSTEM" KEY ("COORDINATE_SYSTEM")
      SOURCE KEY("COORDINATE_SYSTEM") REFERENCES LOCATION_CIM ("COORDINATE_SYSTEM")
      DESTINATION KEY("COORDINATE_SYSTEM") REFERENCES COORDINATE_SYSTEM_CIM ("CIM_URN_UUID")
     LABEL HASLOCATION_COORDINATESYSTEM NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."MEASUREMENT_EXCEPTION" AS "MEASUREMENT_EXCEPTION_HASMETERCHANNEL" KEY ("METER_CHANNEL_ID")
      SOURCE KEY("METER_CHANNEL_ID") REFERENCES MEASUREMENT_EXCEPTION ("METER_CHANNEL_ID")
      DESTINATION KEY("METER_CHANNEL_ID") REFERENCES METER_CHANNEL ("METER_CHANNEL_ID")
     LABEL HASMETERCHANNEL NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."METER_CHANNEL" AS "METER_CHANNEL_HASMETERCONFIGURATION" KEY ("METER_CONFIGURATION_ID")
      SOURCE KEY("METER_CONFIGURATION_ID") REFERENCES METER_CHANNEL ("METER_CONFIGURATION_ID")
      DESTINATION KEY("METER_CONFIGURATION_ID") REFERENCES METER_CONFIGURATION ("METER_CONFIGURATION_ID")
     LABEL HASMETERCONFIGURATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."PARTY" AS "PARTY_REFERENCESORGANIZATION" KEY ("ORGANIZATION_ID")
      SOURCE KEY("ORGANIZATION_ID") REFERENCES PARTY ("ORGANIZATION_ID")
      DESTINATION KEY("ORGANIZATION_ID") REFERENCES ORGANIZATION ("ORGANIZATION_ID")
     LABEL REFERENCESORGANIZATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."PARTY" AS "PARTY_REFERENCESPERSON" KEY ("PERSON_ID")
      SOURCE KEY("PERSON_ID") REFERENCES PARTY ("PERSON_ID")
      DESTINATION KEY("PERSON_ID") REFERENCES PERSON ("PERSON_ID")
     LABEL REFERENCESPERSON NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."POSITION_POINT_CIM" AS "POSITION_POINT_CIM_HASPOSITIONPOINT_LOCATION" KEY ("LOCATION")
      SOURCE KEY("LOCATION") REFERENCES POSITION_POINT_CIM ("LOCATION")
      DESTINATION KEY("LOCATION") REFERENCES LOCATION_CIM ("CIM_URN_UUID")
     LABEL HASPOSITIONPOINT_LOCATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."POWER_TRANSFORMER_CIM" AS "POWER_TRANSFORMER_CIM_HASEQUIPMENT_EQUIPMENTCONTAINER" KEY ("EQUIPMENT_CONTAINER")
      SOURCE KEY("EQUIPMENT_CONTAINER") REFERENCES POWER_TRANSFORMER_CIM ("EQUIPMENT_CONTAINER")
      DESTINATION KEY("EQUIPMENT_CONTAINER") REFERENCES EQUIPMENT_CONTAINER_CIM ("CIM_URN_UUID")
     LABEL HASEQUIPMENT_EQUIPMENTCONTAINER NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."POWER_TRANSFORMER_CIM" AS "POWER_TRANSFORMER_CIM_HASPOWERSYSTEMRESOURCE_LOCATION" KEY ("LOCATION")
      SOURCE KEY("LOCATION") REFERENCES POWER_TRANSFORMER_CIM ("LOCATION")
      DESTINATION KEY("LOCATION") REFERENCES LOCATION_CIM ("CIM_URN_UUID")
     LABEL HASPOWERSYSTEMRESOURCE_LOCATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."SPECIALIZED_SERVICE_CONTRACT" AS "SPECIALIZED_SERVICE_CONTRACT_HASUTILITYACCOUNT" KEY ("UTILITY_ACCOUNT_ID")
      SOURCE KEY("UTILITY_ACCOUNT_ID") REFERENCES SPECIALIZED_SERVICE_CONTRACT ("UTILITY_ACCOUNT_ID")
      DESTINATION KEY("UTILITY_ACCOUNT_ID") REFERENCES UTILITY_ACCOUNT ("UTILITY_ACCOUNT_ID")
     LABEL HASUTILITYACCOUNT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."SUBSTATION_CIM" AS "SUBSTATION_CIM_HASSUBSTATION_NORMALENERGIZEDFEEDER" KEY ("NORMAL_ENERGIZED_FEEDER")
      SOURCE KEY("NORMAL_ENERGIZED_FEEDER") REFERENCES SUBSTATION_CIM ("NORMAL_ENERGIZED_FEEDER")
      DESTINATION KEY("NORMAL_ENERGIZED_FEEDER") REFERENCES FEEDER_CIM ("CIM_URN_UUID")
     LABEL HASSUBSTATION_NORMALENERGIZEDFEEDER NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."SWITCH_PHASE_CIM" AS "SWITCH_PHASE_CIM_HASSWITCHPHASE_SWITCH" KEY ("SWITCH")
      SOURCE KEY("SWITCH") REFERENCES SWITCH_PHASE_CIM ("SWITCH")
      DESTINATION KEY("SWITCH") REFERENCES SWITCH_CIM ("CIM_URN_UUID")
     LABEL HASSWITCHPHASE_SWITCH NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."TERMINAL_CIM" AS "TERMINAL_CIM_HASTERMINAL_CONDUCTINGEQUIPMENT" KEY ("CONDUCTING_EQUIPMENT")
      SOURCE KEY("CONDUCTING_EQUIPMENT") REFERENCES TERMINAL_CIM ("CONDUCTING_EQUIPMENT")
      DESTINATION KEY("CONDUCTING_EQUIPMENT") REFERENCES CONDUCTING_EQUIPMENT_CIM ("CIM_URN_UUID")
     LABEL HASTERMINAL_CONDUCTINGEQUIPMENT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."TERMINAL_CIM" AS "TERMINAL_CIM_HASTERMINAL_CONNECTIVITYNODE" KEY ("CONNECTIVITY_NODE")
      SOURCE KEY("CONNECTIVITY_NODE") REFERENCES TERMINAL_CIM ("CONNECTIVITY_NODE")
      DESTINATION KEY("CONNECTIVITY_NODE") REFERENCES CONNECTIVITY_NODE_CIM ("CIM_URN_UUID")
     LABEL HASTERMINAL_CONNECTIVITYNODE NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."TRANSFORMER_END_INFO_CIM" AS "TRANSFORMER_END_INFO_CIM_HASTRANSFORMERENDINFO_TRANSFORMERTANKINFO" KEY ("TRANSFORMER_TANK_INFO")
      SOURCE KEY("TRANSFORMER_TANK_INFO") REFERENCES TRANSFORMER_END_INFO_CIM ("TRANSFORMER_TANK_INFO")
      DESTINATION KEY("TRANSFORMER_TANK_INFO") REFERENCES TRANSFORMER_TANK_INFO_NODE_CIM ("CIM_URN_UUID")
     LABEL HASTRANSFORMERENDINFO_TRANSFORMERTANKINFO NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."TRANSFORMER_TANK_CIM" AS "TRANSFORMER_TANK_CIM_HASTRANSFORMERTANK_POWERTRANSFORMER" KEY ("POWER_TRANSFORMER")
      SOURCE KEY("POWER_TRANSFORMER") REFERENCES TRANSFORMER_TANK_CIM ("POWER_TRANSFORMER")
      DESTINATION KEY("POWER_TRANSFORMER") REFERENCES POWER_TRANSFORMER_CIM ("CIM_URN_UUID")
     LABEL HASTRANSFORMERTANK_POWERTRANSFORMER NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."TRANSFORMER_TANK_CIM" AS "TRANSFORMER_TANK_CIM_HASTRANSFORMERTANK_TRANSFORMERTANKINFO" KEY ("TRANSFORMER_TANK_INFO")
      SOURCE KEY("TRANSFORMER_TANK_INFO") REFERENCES TRANSFORMER_TANK_CIM ("TRANSFORMER_TANK_INFO")
      DESTINATION KEY("TRANSFORMER_TANK_INFO") REFERENCES TRANSFORMER_TANK_INFO_NODE_CIM ("CIM_URN_UUID")
     LABEL HASTRANSFORMERTANK_TRANSFORMERTANKINFO NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."TRANSFORMER_TANK_END_CIM" AS "TRANSFORMER_TANK_END_CIM_HASTRANSFORMEREND_BASEVOLTAGE" KEY ("BASE_VOLTAGE")
      SOURCE KEY("BASE_VOLTAGE") REFERENCES TRANSFORMER_TANK_END_CIM ("BASE_VOLTAGE")
      DESTINATION KEY("BASE_VOLTAGE") REFERENCES BASE_VOLTAGE_CIM ("CIM_URN_UUID")
     LABEL HASTRANSFORMEREND_BASEVOLTAGE NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."TRANSFORMER_TANK_END_CIM" AS "TRANSFORMER_TANK_END_CIM_HASTRANSFORMEREND_TERMINAL" KEY ("TERMINAL")
      SOURCE KEY("TERMINAL") REFERENCES TRANSFORMER_TANK_END_CIM ("TERMINAL")
      DESTINATION KEY("TERMINAL") REFERENCES TERMINAL_CIM ("CIM_URN_UUID")
     LABEL HASTRANSFORMEREND_TERMINAL NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."TRANSFORMER_TANK_END_CIM" AS "TRANSFORMER_TANK_END_CIM_HASTRANSFORMERTANKEND_TRANSFORMERTANK" KEY ("TRANSFORMER_TANK")
      SOURCE KEY("TRANSFORMER_TANK") REFERENCES TRANSFORMER_TANK_END_CIM ("TRANSFORMER_TANK")
      DESTINATION KEY("TRANSFORMER_TANK") REFERENCES TRANSFORMER_TANK_CIM ("CIM_URN_UUID")
     LABEL HASTRANSFORMERTANKEND_TRANSFORMERTANK NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."UTILITY_ACCOUNT" AS "UTILITY_ACCOUNT_HASPARTY" KEY ("PARTY_ID")
      SOURCE KEY("PARTY_ID") REFERENCES UTILITY_ACCOUNT ("PARTY_ID")
      DESTINATION KEY("PARTY_ID") REFERENCES PARTY ("PARTY_ID")
     LABEL HASPARTY NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."UTILITY_BILL" AS "UTILITY_BILL_HASUTILITYACCOUNT" KEY ("UTILITY_ACCOUNT_ID")
      SOURCE KEY("UTILITY_ACCOUNT_ID") REFERENCES UTILITY_BILL ("UTILITY_ACCOUNT_ID")
      DESTINATION KEY("UTILITY_ACCOUNT_ID") REFERENCES UTILITY_ACCOUNT ("UTILITY_ACCOUNT_ID")
     LABEL HASUTILITYACCOUNT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."UTILITY_BILL_SERVICE_LINE_ITEM" AS "UTILITY_BILL_SERVICE_LINE_ITEM_HASUTILITYBILL" KEY ("UTILITY_BILL_ID")
      SOURCE KEY("UTILITY_BILL_ID") REFERENCES UTILITY_BILL_SERVICE_LINE_ITEM ("UTILITY_BILL_ID")
      DESTINATION KEY("UTILITY_BILL_ID") REFERENCES UTILITY_BILL ("UTILITY_BILL_ID")
     LABEL HASUTILITYBILL NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."UTILITY_BILL_SERVICE_PERIOD" AS "UTILITY_BILL_SERVICE_PERIOD_HASUTILITYBILL" KEY ("UTILITY_BILL_ID")
      SOURCE KEY("UTILITY_BILL_ID") REFERENCES UTILITY_BILL_SERVICE_PERIOD ("UTILITY_BILL_ID")
      DESTINATION KEY("UTILITY_BILL_ID") REFERENCES UTILITY_BILL ("UTILITY_BILL_ID")
     LABEL HASUTILITYBILL NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."UTILITY_BILL_SERVICE_SUMMARY" AS "UTILITY_BILL_SERVICE_SUMMARY_HASUTILITYBILL" KEY ("UTILITY_BILL_ID")
      SOURCE KEY("UTILITY_BILL_ID") REFERENCES UTILITY_BILL_SERVICE_SUMMARY ("UTILITY_BILL_ID")
      DESTINATION KEY("UTILITY_BILL_ID") REFERENCES UTILITY_BILL ("UTILITY_BILL_ID")
     LABEL HASUTILITYBILL NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."UTILITY_BILL_SERVICE_SUMMARY" AS "UTILITY_BILL_SERVICE_SUMMARY_HASUTILITYLOCATION" KEY ("UTILITY_LOCATION_ID")
      SOURCE KEY("UTILITY_LOCATION_ID") REFERENCES UTILITY_BILL_SERVICE_SUMMARY ("UTILITY_LOCATION_ID")
      DESTINATION KEY("UTILITY_LOCATION_ID") REFERENCES UTILITY_LOCATION ("UTILITY_LOCATION_ID")
     LABEL HASUTILITYLOCATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."UTILITY_BILL_SERVICE_SUMMARY" AS "UTILITY_BILL_SERVICE_SUMMARY_HASUTILITYSERVICECONTRACT" KEY ("UTILITY_SERVICE_CONTRACT_ID")
      SOURCE KEY("UTILITY_SERVICE_CONTRACT_ID") REFERENCES UTILITY_BILL_SERVICE_SUMMARY ("UTILITY_SERVICE_CONTRACT_ID")
      DESTINATION KEY("UTILITY_SERVICE_CONTRACT_ID") REFERENCES ELECTRIC_SERVICE_CONTRACT ("UTILITY_SERVICE_CONTRACT_ID")
     LABEL HASUTILITYSERVICECONTRACT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."UTILITY_BILL_SERVICE_USAGE" AS "UTILITY_BILL_SERVICE_USAGE_HASUTILITYBILL" KEY ("UTILITY_BILL_ID")
      SOURCE KEY("UTILITY_BILL_ID") REFERENCES UTILITY_BILL_SERVICE_USAGE ("UTILITY_BILL_ID")
      DESTINATION KEY("UTILITY_BILL_ID") REFERENCES UTILITY_BILL ("UTILITY_BILL_ID")
     LABEL HASUTILITYBILL NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."UTILITY_BILL_USAGE_DISAGGREGATION" AS "UTILITY_BILL_USAGE_DISAGGREGATION_HASUTILITYACCOUNT" KEY ("UTILITY_ACCOUNT_ID")
      SOURCE KEY("UTILITY_ACCOUNT_ID") REFERENCES UTILITY_BILL_USAGE_DISAGGREGATION ("UTILITY_ACCOUNT_ID")
      DESTINATION KEY("UTILITY_ACCOUNT_ID") REFERENCES UTILITY_ACCOUNT ("UTILITY_ACCOUNT_ID")
     LABEL HASUTILITYACCOUNT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."UTILITY_LOCATION" AS "UTILITY_LOCATION_HASPARENTUTILITYLOCATION" KEY ("PARENT_UTILITY_LOCATION_ID")
      SOURCE KEY("PARENT_UTILITY_LOCATION_ID") REFERENCES UTILITY_LOCATION ("PARENT_UTILITY_LOCATION_ID")
      DESTINATION KEY("PARENT_UTILITY_LOCATION_ID") REFERENCES UTILITY_LOCATION ("UTILITY_LOCATION_ID")
     LABEL HASPARENTUTILITYLOCATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."VOLTAGE_LEVEL_CIM" AS "VOLTAGE_LEVEL_CIM_HASVOLTAGELEVEL_BASEVOLTAGE" KEY ("BASE_VOLTAGE")
      SOURCE KEY("BASE_VOLTAGE") REFERENCES VOLTAGE_LEVEL_CIM ("BASE_VOLTAGE")
      DESTINATION KEY("BASE_VOLTAGE") REFERENCES BASE_VOLTAGE_CIM ("CIM_URN_UUID")
     LABEL HASVOLTAGELEVEL_BASEVOLTAGE NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."VOLTAGE_LEVEL_CIM" AS "VOLTAGE_LEVEL_CIM_HASVOLTAGELEVEL_SUBSTATION" KEY ("SUBSTATION")
      SOURCE KEY("SUBSTATION") REFERENCES VOLTAGE_LEVEL_CIM ("SUBSTATION")
      DESTINATION KEY("SUBSTATION") REFERENCES SUBSTATION_CIM ("CIM_URN_UUID")
     LABEL HASVOLTAGELEVEL_SUBSTATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."WASTEWATER_SERVICE_CONTRACTED_ITEM" AS "WASTEWATER_SERVICE_CONTRACTED_ITEM_HASSERVICEPOINT" KEY ("UTILITY_SERVICE_POINT_ID")
      SOURCE KEY("UTILITY_SERVICE_POINT_ID") REFERENCES WASTEWATER_SERVICE_CONTRACTED_ITEM ("UTILITY_SERVICE_POINT_ID")
      DESTINATION KEY("UTILITY_SERVICE_POINT_ID") REFERENCES WASTEWATER_SERVICE_POINT ("UTILITY_SERVICE_POINT_ID")
     LABEL HASSERVICEPOINT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."WASTEWATER_SERVICE_CONTRACTED_ITEM" AS "WASTEWATER_SERVICE_CONTRACTED_ITEM_HASUTILITYSERVICECONTRACT" KEY ("UTILITY_SERVICE_CONTRACT_ID")
      SOURCE KEY("UTILITY_SERVICE_CONTRACT_ID") REFERENCES WASTEWATER_SERVICE_CONTRACTED_ITEM ("UTILITY_SERVICE_CONTRACT_ID")
      DESTINATION KEY("UTILITY_SERVICE_CONTRACT_ID") REFERENCES WASTEWATER_SERVICE_CONTRACT ("UTILITY_SERVICE_CONTRACT_ID")
     LABEL HASUTILITYSERVICECONTRACT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."WASTEWATER_SERVICE_CONTRACT" AS "WASTEWATER_SERVICE_CONTRACT_HASUTILITYACCOUNT" KEY ("UTILITY_ACCOUNT_ID")
      SOURCE KEY("UTILITY_ACCOUNT_ID") REFERENCES WASTEWATER_SERVICE_CONTRACT ("UTILITY_ACCOUNT_ID")
      DESTINATION KEY("UTILITY_ACCOUNT_ID") REFERENCES UTILITY_ACCOUNT ("UTILITY_ACCOUNT_ID")
     LABEL HASUTILITYACCOUNT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."WASTEWATER_SERVICE_POINT" AS "WASTEWATER_SERVICE_POINT_HASUTILITYLOCATION" KEY ("UTILITY_LOCATION_ID")
      SOURCE KEY("UTILITY_LOCATION_ID") REFERENCES WASTEWATER_SERVICE_POINT ("UTILITY_LOCATION_ID")
      DESTINATION KEY("UTILITY_LOCATION_ID") REFERENCES UTILITY_LOCATION ("UTILITY_LOCATION_ID")
     LABEL HASUTILITYLOCATION NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."WATER_METER_INSTALLATION" AS "WATER_METER_INSTALLATION_HASCOMMODITYMETER" KEY ("UTILITY_METER_ID")
      SOURCE KEY("UTILITY_METER_ID") REFERENCES WATER_METER_INSTALLATION ("UTILITY_METER_ID")
      DESTINATION KEY("UTILITY_METER_ID") REFERENCES WATER_METER ("UTILITY_METER_ID")
     LABEL HASCOMMODITYMETER NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."WATER_METER_INSTALLATION" AS "WATER_METER_INSTALLATION_HASSERVICEPOINT" KEY ("UTILITY_SERVICE_POINT_ID")
      SOURCE KEY("UTILITY_SERVICE_POINT_ID") REFERENCES WATER_METER_INSTALLATION ("UTILITY_SERVICE_POINT_ID")
      DESTINATION KEY("UTILITY_SERVICE_POINT_ID") REFERENCES WATER_SERVICE_POINT ("UTILITY_SERVICE_POINT_ID")
     LABEL HASSERVICEPOINT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."WATER_SERVICE_CONTRACTED_ITEM" AS "WATER_SERVICE_CONTRACTED_ITEM_HASSERVICEPOINT" KEY ("UTILITY_SERVICE_POINT_ID")
      SOURCE KEY("UTILITY_SERVICE_POINT_ID") REFERENCES WATER_SERVICE_CONTRACTED_ITEM ("UTILITY_SERVICE_POINT_ID")
      DESTINATION KEY("UTILITY_SERVICE_POINT_ID") REFERENCES WATER_SERVICE_POINT ("UTILITY_SERVICE_POINT_ID")
     LABEL HASSERVICEPOINT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."WATER_SERVICE_CONTRACTED_ITEM" AS "WATER_SERVICE_CONTRACTED_ITEM_HASUTILITYSERVICECONTRACT" KEY ("UTILITY_SERVICE_CONTRACT_ID")
      SOURCE KEY("UTILITY_SERVICE_CONTRACT_ID") REFERENCES WATER_SERVICE_CONTRACTED_ITEM ("UTILITY_SERVICE_CONTRACT_ID")
      DESTINATION KEY("UTILITY_SERVICE_CONTRACT_ID") REFERENCES WATER_SERVICE_CONTRACT ("UTILITY_SERVICE_CONTRACT_ID")
     LABEL HASUTILITYSERVICECONTRACT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."WATER_SERVICE_CONTRACT" AS "WATER_SERVICE_CONTRACT_HASUTILITYACCOUNT" KEY ("UTILITY_ACCOUNT_ID")
      SOURCE KEY("UTILITY_ACCOUNT_ID") REFERENCES WATER_SERVICE_CONTRACT ("UTILITY_ACCOUNT_ID")
      DESTINATION KEY("UTILITY_ACCOUNT_ID") REFERENCES UTILITY_ACCOUNT ("UTILITY_ACCOUNT_ID")
     LABEL HASUTILITYACCOUNT NO PROPERTIES,
   "INDUSTRY_EW#MODEL"."WATER_SERVICE_POINT" AS "WATER_SERVICE_POINT_HASUTILITYLOCATION" KEY ("UTILITY_LOCATION_ID")
      SOURCE KEY("UTILITY_LOCATION_ID") REFERENCES WATER_SERVICE_POINT ("UTILITY_LOCATION_ID")
      DESTINATION KEY("UTILITY_LOCATION_ID") REFERENCES UTILITY_LOCATION ("UTILITY_LOCATION_ID")
     LABEL HASUTILITYLOCATION NO PROPERTIES )
  OPTIONS (TRUSTED MODE, ALLOW MIXED PROPERTY TYPES);
/